#!/bin/sh
set -e
ln -sf /usr/bin/lsgpu.py /usr/bin/lsgpu
if [ -f /usr/share/doc/lsgpu/lsgpu.1 ]; then
    cp /usr/share/doc/lsgpu/lsgpu.1 /usr/share/man/man1/ 2>/dev/null || true
    mandb -q 2>/dev/null || true
fi
